### ISSUE TITLE
Integration error

### ISSUE THREAD

**Issue by ZeinBader** [HuangLab-CBI/PhasiHunter#9]
this error comes when i follow your command 
zein@zein-HP-Pavilion-All-in-One-Desktop-27-ca2xxx:/media/zein/Data/PhasiHunter$ phasiHunter integration -io phase_o.txt -ia phase_a.txt -an oryza_sativa_gdna.gff3 -g y -o integration_o.txt -a integration_a.txt -s integration_s.txt -po integration_p.txt -j 1 -pn 4 -pl 21 -pv 0.001 -il 5
Start run integration.py at 2024-01-05-11-18-15
Threads: 1
Traceback (most recent call last):
  File "/home/zein/PhasiHunter/bin/integration.py", line 273, in <module>
    main1()
  File "/home/zein/PhasiHunter/bin/integration.py", line 166, in main1
    fo_intergration_tmp = open(tmp_fo_intergration, 'w')
FileNotFoundError: [Errno 2] No such file or directory: '/2024-01-05-11-18-15_tmpfolder/integration_s.txt_2024-01-05-11-18-15_integration'

and after removing -s option

zein@zein-HP-Pavilion-All-in-One-Desktop-27-ca2xxx:/media/zein/Data/PhasiHunter$ phasiHunter integration -io phase_o.txt -ia phase_a.txt -an oryza_sativa_gdna.gff3 -g y -o integration_o.txt -a integration_a.txt -po integration_p.txt -j 1 -pn 4 -pl 21 -pv 0.001 -il 5
Start run integration.py at 2024-01-05-11-19-10
Threads: 1
Loading data
Merging phasiRNA clusters
Annotating phasiRNA clusters
Deduplication & Classification
Traceback (most recent call last):
  File "/home/zein/PhasiHunter/bin/integration.py", line 273, in <module>
    main1()
  File "/home/zein/PhasiHunter/bin/integration.py", line 225, in main1
    tmp_intergration = Write_new(hout, pout, hanno, panno, p_phasiRNA_cluster, fo_phasiRNA, fo_allsiRNA, transcriptAnno, flnc_anno_dic)
  File "/home/zein/PhasiHunter/bin/integrationFunction.py", line 1384, in Write_new
    annotation = feature + ":" + gene
TypeError: unsupported operand type(s) for +: 'collections.defaultdict' and 'str'

how can i use it ?

**Comment by ghost** [comment]
The first bug occurred due to a relative path loading error.
The second bug arose from an error in parsing the ensemble reference, as PhasiHunter was primarily developed based on the NCBI reference in earlier versions.
Recently, I rewrite the code and fixed the aforementioned bugs.
Update information can be found at [this link](https://github.com/HuangLab-CBI/PhasiHunter?tab=readme-ov-file#update-log).
I apologize for the delayed reply.
